package dew.rudok.app.gui.swing.message;

public enum EventType {

    ERROR, CANNOT_ADD_CHILD, CANNOT_ADD_CHILD_TO_LEAF, NODE_NOT_SELECTED, AUTHOR_PROJECT_NOT_SELECTED,MUST_INSERT_NAME, CANNOT_DELETE_FILE, CANNOT_DELETE_NODE, RESOURCE_NOT_FOUND, NODE_ALREADY_EXISTS

}
