package dsw.gerumap.app.gui.swing.message;

public enum EventType {

    ERROR, CANNOT_DELETE_PROJECT_EXPLORER, CANNOT_ADD_CHILD_TO_LEAF, NODE_NOT_SELECTED, PROJECT_NOT_SELECTED, MUST_INSERT_NAME, MUST_SET_AUTHOR

}
